name: saocom
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - geopandas
  - rasterio
  - matplotlib
  - jupyterlab
  - pip:
      - ruff
      - black
      - isort
      - nbstripout
