name: saocom-dem-validation
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.9

  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0

  # Geospatial libraries
  - geopandas>=0.13.0
  - shapely>=2.0.0
  - rasterio>=1.3.0
  - pyproj>=3.5.0
  - gdal>=3.6.0

  # Machine learning
  - scikit-learn>=1.3.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.14.0

  # Jupyter
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.5.0

  # Development tools
  - pytest>=7.0.0
  - black>=23.0.0
  - flake8>=6.0.0

  # Pip packages not available in conda
  - pip
  - pip:
    - matplotlib-scalebar>=0.8.0
    - dbfread>=2.0.7
